apiVersion: apps.isadba.com/v1
kind: Application
metadata:
  name: application-sample
  labels:
    app: nginx
spec:
  # TODO(user): Add fields here
  deployment:
    replicas: 2
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels: 
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.18
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
  service:
    ports:
    - name: http
      port: 80
      protocol: TCP
    type: ClusterIP
    selector:
      app: nginx